-- 创建表
CREATE TABLE `role` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT COMMENT '角色Id',
  `RolesName` VARCHAR(256) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '角色名称',
  `Remark` VARCHAR(256) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '描述',
  `Page` VARCHAR(2048) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '角色具有的权限',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8;

CREATE TABLE `user` (
  `UserID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户唯一标识',
  `UserName` VARCHAR(64) NOT NULL COMMENT '用户名称',
  `UserAccount` VARBINARY(64) NOT NULL COMMENT '用户账号',
  `UserPwd` VARCHAR(64) NOT NULL COMMENT '用户密码',
  `UserRole` INT(10) NOT NULL COMMENT '用户角色',
  `IfSuper` TINYINT(1) NOT NULL COMMENT '是否超级用户',
  `Status` INT(10) NOT NULL COMMENT '状态(0-正常，-1-锁定)',
  `LastLoginIP` VARCHAR(128) DEFAULT NULL COMMENT '上次登陆IP',
  `LastLoginTime` DATETIME NOT NULL DEFAULT '1900-01-01 00:00:00' COMMENT '上次登陆时间',
  `Crdate` DATETIME DEFAULT NULL COMMENT '添加时间',
  PRIMARY KEY (`UserID`),
  UNIQUE KEY `UserName` (`UserName`)
) ENGINE=INNODB AUTO_INCREMENT=312 DEFAULT CHARSET=utf8;

CREATE TABLE `user_operation_log` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '日志唯一标识',
  `UserID` INT(10) UNSIGNED NOT NULL COMMENT '操作用户唯一标识',
  `UserName` VARCHAR(32) NOT NULL COMMENT '操作用户名称',
  `OperationName` VARCHAR(100) NOT NULL COMMENT '操作说明',
  `OperationMothod` VARCHAR(50) NOT NULL COMMENT '操作方法',
  `OperationData` TEXT NOT NULL COMMENT '操作数据内容',
  `ReturnData` TEXT NOT NULL COMMENT '返回数据',
  `Crdate` DATETIME NOT NULL COMMENT '操作时间',
  PRIMARY KEY (`ID`),
  KEY `IX_UserID` (`UserID`)
) ENGINE=INNODB AUTO_INCREMENT=232 DEFAULT CHARSET=utf8 COMMENT='操作日志';

-- 重置表
TRUNCATE  TABLE `user_operation_log`;

TRUNCATE  TABLE `user`;
TRUNCATE  TABLE `role`;
INSERT INTO `user` (UserID, UserName,UserAccount,UserPwd,UserRole,IfSuper,STATUS,LastLoginIP,LastLoginTime,Crdate) 
VALUES (1,"超级管理员","admin","E10ADC3949BA59ABBE56E057F20F883E",1,1,0,"::1","1900-01-01 00:00:00","1900-01-01 00:00:00");
INSERT INTO `role` (ID, RolesName,Remark,Page) 
VALUES (1,"管理员","老大","1,1.1,1.2,1.3,1.4,1.5,2,2.1,2.2,2.3,2.4,2.5,2.6,2.7,2.8,3,3.1,3.2,3.3,3.4,4,4.1,4.2,4.3,5,5.1,5.2,5.3,6,100001,100002,100003,100004,100005,100006");